### PR TITLE
Manually po file fixes

### PR DESCRIPTION
**Pull request by StefWe**
Add manually fixes to the translation files see issue #3

### CODE REVIEW

**Comment by Flohack74** [comment]
I had to unfortunately merge another pending changes from Weblate, you need to resolve the conflict :)

**Comment by Flohack74** [comment]
But the translation is locked now, until we clean this up, so it wont happen a second time...

**Comment by Flohack74** [comment]
Nevermind fixed it myself, was only a small thing ;)

**Comment by StefWe** [comment]
Thank you for your help.

**Comment by Flohack74** [comment]
In another case, Weblate was able to repair the same problem automatically:
grafik

**Comment by Flohack74** [comment]
You can see all build from CI here: https://ci.ubports.com/blue/organizations/jenkins/ubports%2Fubuntu-ui-extras/activity?branch=xenial - The last build was fine, even already one after my fix merge. So the only problem can be that it is not updated into the images, maybe its not even marked for installation. I will check...

**Pull request merged**
