### PR TITLE
Exposure

### PR DESCRIPTION
**Pull request by StefWe**
The exposure can be edited.

screenshot20190412_224646238
screenshot20190412_224658782
screenshot20190412_224706750
screenshot20190412_224716957

### CODE REVIEW

**Comment by StefWe** [comment]
@Flohack74 @UniversalSuperBox can someone restart the build on the jenkins to check if everything is right with my pr?
Thank you very much

**Comment by Flohack74** [comment]
I did but it failed again. We need to check whats wrong...

**Comment by StefWe** [comment]
Thank you very much for your effort

**Review by Flohack74 — APPROVED** [review]

**Comment by advocatux** [comment]
I can confirm that the exposure feature is working fine.
- Device: Nexus 5 (`hammerhead`)
- Channel: `rc`
- Build: Ubuntu 16.04 (`2019-W18`)

**Comment by Danfro** [comment]
Works fine on E5 with RC channel 2019-W18. :+1:

**Comment by jezek** [comment]
FP2 (2019-W18)
Exposure works

**Comment by ziggutas** [comment]
BQ E4.5 rc (2019-W18)
Exposure setting works

**Comment by ziggutas** [comment]
Nexus 7 (flo) rc (2019-W18)
Exposure works

**Pull request merged**
