### PR TITLE
UbuntuColors to theme palette, update components

### PR DESCRIPTION
**Pull request by cibersheep**
Don't merge until I can test this on device and projects that uses Extras: ie Gallery

- UbuntuColors -> theme.palette
- Bumped QtQuick, Components version
- Update BusyIndicator (test!)

### CODE REVIEW

**Review by Flohack74 — APPROVED** [review]

**Comment by Flohack74** [comment]
I like how old and deprecated this was ^^

**Comment by Flohack74** [comment]
Oh sorry did not read your comment. Please in the future create is as draft (new function in Github)

**Comment by cibersheep** [comment]
^___^ let's test tonight when arrive to the dev.

**Comment by Flohack74** [comment]
Oki I agree, if we break stuff its ok ^^

**Comment by cibersheep** [comment]
Looks ok for now.
Only crop button, that doesn't respect the theme but that's because how it's implemented in the project. Something to look soon

**Pull request merged**
